SET SCHEMA FN72097;
CREATE VIEW INFO10
    AS
      SELECT F.NAME, F.GOALS,T.CITY
      FROM FOOTBALLER F,TEAM T
      WHERE T.NAME=F.TEAM_NAME
      AND F.NAME LIKE 'J%';

SELECT * FROM INFO10;

CREATE VIEW INFO11
    AS
     SELECT R.WORK_NUMBER, M.TEAM_NAME1,M.RESULT,M.TEAM_NAME2
     FROM REFEREE R, MATCH M
      WHERE M.REFEREE_NAME=R.NAME
      AND R.CITY = 'Plovdiv'
      AND M.TEAM_NAME1='CSKA';

SELECT * FROM INFO11;
